# Generated by Django 4.2.11 on 2024-06-24 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0004_alter_saving_amount'),
        ('wagubumbuzi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagubumbuzi',
            name='saving_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saving.saving'),
        ),
    ]
