# Generated by Django 4.2.11 on 2024-06-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagubumbuzi', '0002_wagubumbuzi_saving_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagubumbuzi',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
