# Generated by Django 4.2.11 on 2024-12-14 08:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagubumbuzi', '0003_alter_wagubumbuzi_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagubumbuzi',
            name='total_after_reduction',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
