# Generated by Django 4.2.11 on 2025-01-02 08:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagubumbuzi', '0004_wagubumbuzi_total_after_reduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagubumbuzi',
            name='amount_reduced',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
