# Generated by Django 4.2.11 on 2025-04-06 09:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagubumbuzi', '0005_wagubumbuzi_amount_reduced'),
    ]

    operations = [
        migrations.CreateModel(
            name='WagubumbuziReduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_reduced', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_after_reduction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='wagubumbuzi',
            name='amount_reduced',
        ),
        migrations.RemoveField(
            model_name='wagubumbuzi',
            name='total_after_reduction',
        ),
    ]
