# Generated by Django 4.2.11 on 2024-05-21 07:17

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=userprofile.models.upload_to),
        ),
    ]
