# Generated by Django 4.2.11 on 2024-07-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_userprofile_gender_userprofile_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
