# Generated by Django 4.2.11 on 2024-06-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='saving',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='date_of_payment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
