# Generated by Django 4.2.11 on 2024-06-04 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saving', '0002_saving_created_at_saving_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
