# Generated by Django 4.2.11 on 2024-06-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0003_alter_saving_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
