# Generated by Django 4.2.11 on 2024-07-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0004_alter_saving_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='member_name',
        ),
    ]
