# Generated by Django 4.2.11 on 2024-05-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
