# Generated by Django 4.2.11 on 2024-06-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loan_created_at_loan_updated_at_alter_loan_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
