# Generated by Django 4.2.11 on 2024-07-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_alter_loan_amount_alter_loan_remaining_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='member_name',
        ),
    ]
