# Generated by Django 4.2.11 on 2024-09-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_remove_loan_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
