# Generated by Django 4.2.11 on 2024-09-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_loan_loan_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
