# Generated by Django 4.2.11 on 2025-04-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_alter_loan_loan_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
