# Generated by Django 4.2.11 on 2024-06-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A Member with that Membership ID already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits, and spaces only.', max_length=150, unique=True),
        ),
    ]
