# Generated by Django 4.2.11 on 2024-07-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0002_alter_borrower_membership_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='name',
        ),
    ]
