# Generated by Django 4.2.11 on 2024-07-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='penality',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
